#! /bin/bash

echo 'Cleaning ...'
moveArray=( 'amplifier.pulse' 'cherenkov.photons' 'detector.pulse' 'detector.signals' 'fadc.aver' 'fadc.dave' 'fadc.daver' 'fadc.deco' 'fadc.samples' 'fadc.shaped' 'fadc.shapin' 'flasim.test' 'nsb.photons' 'photon.bunches' 'thermal.photons' )
for item in ${moveArray[@]}; do
    if [ -e ${item} ]; then
	rm -vrf ${item}
    fi
done
echo 'Done.'


