#! /bin/bash

outputDir=$1

if [ ! -d ${outputDir} ]; then
    mkdir -p ${outputDir}
    echo "Created ${outputDir}."
else
    echo "${outputDir} exists. Overwrite? [y/n] [ENTER]"
    read ifOverwrite

    if [ ${ifOverwrite} == 'y' ]; then
	rm -rf ${outputDir}
	mkdir -p ${outputDir}
	echo "Created ${outputDir}."
    else
	echo "Skip."
    fi
fi

echo 'Copying ...'
copyArray=( 'cadisi.f90' 'cadisi.par' 'mppcspenormean.dat' )
for item in ${copyArray[@]}; do
    cp -v ${item} ${outputDir}
done
echo 'Done.'

echo 'Moving ...'
moveArray=( 'amplifier.pulse' 'cherenkov.photons' 'detector.pulse' 'detector.signals' 'fadc.aver' 'fadc.dave' 'fadc.daver' 'fadc.deco' 'fadc.samples' 'fadc.shaped' 'fadc.shapin' 'flasim.test' 'nsb.photons' 'photon.bunches' 'thermal.photons' 'cadisi.results' )
for item in ${moveArray[@]}; do
    if [ -e ${item} ]; then
	mv -v ${item} ${outputDir}
    fi
done
echo 'Done.'


